PRO ex16
PSOPEN, SPACE2=800
f=SF('gdata.nc', 'u', MEAN='lon')
LEVS, MIN=-32, MAX=32, STEP=4
CS, SCALE=1
GSET, XMIN=-90, XMAX=90, YMIN=1000, YMAX=0
CON, F=f, TITLE='Jan 1987 - Zonal Mean Zonal Wind', $
     NEGATIVE_STYLE=2, ZERO_THICK=200,CB_TITLE='ms!E-1!N', /NOFILL
PFILL, FIELD=f.data, X=f.lat, Y=f.p, MIN=28, MAX=100, STYLE=6
AXES, XSTEP=30, XTITLE='Latitude', YSTEP=-250, YTITLE='Pressure (mb)'
PSCLOSE
END

