PRO ex52
d=NCREAD('rgp.nc')
PSOPEN
CS, SCALE=1, NCOLS=24
GSET, XMIN=0, XMAX=N_ELEMENTS(d.x)-1, YMIN=0, YMAX=N_ELEMENTS(d.y)-1 
LEVS, MIN=980, MAX=1035, STEP=2.5, NDECS=1
CON, X=FINDGEN(N_ELEMENTS(d.x))+0.5, Y=FINDGEN(N_ELEMENTS(d.y))+0.5, $
     FIELD=REVERSE(d.p, 2), /CB_ALT, CB_TITLE='Surface Pressure (mb)'
RGAXES, XIN=d.x, YIN=d.y, XPOLE=160, YPOLE=30
PSCLOSE
END

