PRO ex53
d=NCREAD('af4km.nc')
PSOPEN
CS, SCALE=1, NCOLS=22
GSET, XMIN=0, XMAX=N_ELEMENTS(d.x)-1, YMIN=0, YMAX=N_ELEMENTS(d.y)-1  
LEVS, MIN=120, MAX=320, STEP=10
CON, FIELD=d.olr, X=INDGEN(N_ELEMENTS(d.x)), Y=INDGEN(N_ELEMENTS(d.y)),$
     CB_TITLE='OLR (wm-2)', /IMG, /NOLINES
RGAXES, XIN=d.x, YIN=d.y, XPOLE=180, YPOLE=79, /COUNTRIES
PSCLOSE
END

