PRO gd3
PSOPEN, AXISTYPE=2, FONT=7, CHARSIZE=130, TFONT=7, TCHARSIZE=180, $
        CFONT=7, CCHARSIZE=120
CS, SCALE=1	
MAP
LEVS, MIN=-64, MAX=64, STEP=8
CON, F=SF('gdata.nc', 'u', p=1), TITLE='Zonal Wind at 1mb'
PSCLOSE
END

